export const products = [
  // ===== WEIGHT LOSS PEPTIDES =====
  {
    id: 'tirz5',
    name: 'Tirzepatide 5mg',
    slug: 'tirzepatide-5mg',
    description: 'GLP-1/GIP dual agonist for metabolic research',
    price: 35,
    originalPrice: 40,
    category: 'Weight Loss',
    subcategory: 'GLP-1 Agonists',
    dosage: '5mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    molecularWeight: '4813.5 Da',
    sequence: 'Tyr-Aib-Glu-Gly-Thr-Phe-Thr-Ser-Asp-Tyr-Ser-Ile-Ala-Met-Asp-Lys-Ile-His-Gln-Tyr-Val',
    storage: '-20°C',
    inStock: true,
    featured: true,
  },
  {
    id: 'tirz100',
    name: 'Tirzepatide 100mg',
    slug: 'tirzepatide-100mg',
    description: 'High-dose GLP-1/GIP dual agonist',
    price: 270,
    originalPrice: 280,
    category: 'Weight Loss',
    subcategory: 'GLP-1 Agonists',
    dosage: '100mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    storage: '-20°C',
    inStock: true,
  },
  {
    id: 'sema2',
    name: 'Semaglutide 2mg',
    slug: 'semaglutide-2mg',
    description: 'GLP-1 receptor agonist for metabolic studies',
    price: 25,
    originalPrice: 30,
    category: 'Weight Loss',
    subcategory: 'GLP-1 Agonists',
    dosage: '2mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    molecularWeight: '4113.6 Da',
    storage: '-20°C',
    inStock: true,
    featured: true,
  },
  {
    id: 'sema30',
    name: 'Semaglutide 30mg',
    slug: 'semaglutide-30mg',
    description: 'High-potency GLP-1 agonist',
    price: 95,
    originalPrice: 100,
    category: 'Weight Loss',
    subcategory: 'GLP-1 Agonists',
    dosage: '30mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    storage: '-20°C',
    inStock: true,
  },
  {
    id: 'reta5',
    name: 'Retatrutide 5mg',
    slug: 'retatrutide-5mg',
    description: 'GLP-1/GIP/GCGR triple agonist research',
    price: 60,
    originalPrice: 65,
    category: 'Weight Loss',
    subcategory: 'Triple Agonists',
    dosage: '5mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    storage: '-20°C',
    inStock: true,
    featured: true,
  },
  {
    id: 'reta60',
    name: 'Retatrutide 60mg',
    slug: 'retatrutide-60mg',
    description: 'High-dose triple agonist',
    price: 300,
    originalPrice: 310,
    category: 'Weight Loss',
    subcategory: 'Triple Agonists',
    dosage: '60mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    storage: '-20°C',
    inStock: true,
  },

  // ===== RECOVERY & HEALING PEPTIDES =====
  {
    id: 'bpc5',
    name: 'BPC-157 5mg',
    slug: 'bpc-157-5mg',
    description: 'Body Protection Compound for tissue repair',
    price: 30,
    originalPrice: 35,
    category: 'Recovery',
    subcategory: 'Healing Peptides',
    dosage: '5mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    molecularWeight: '1419.57 Da',
    sequence: 'Gly-Glu-Pro-Pro-Pro-Gly-Lys-Pro-Ala-Asp-Asp-Ala-Gly-Leu-Val',
    halfLife: '4-6 hours',
    storage: '-20°C',
    inStock: true,
    featured: true,
  },
  {
    id: 'bpc20',
    name: 'BPC-157 20mg',
    slug: 'bpc-157-20mg',
    description: 'High-dose tissue repair peptide',
    price: 90,
    originalPrice: 95,
    category: 'Recovery',
    subcategory: 'Healing Peptides',
    dosage: '20mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    storage: '-20°C',
    inStock: true,
  },
  {
    id: 'tb500-5',
    name: 'TB-500 5mg',
    slug: 'tb-500-5mg',
    description: 'Thymosin Beta-4 for muscle recovery',
    price: 60,
    originalPrice: 65,
    category: 'Recovery',
    subcategory: 'Healing Peptides',
    dosage: '5mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    molecularWeight: '4963.5 Da',
    sequence: 'Ac-Ser-Asp-Lys-Pro-Asp-Met-Ala-Glu-Ile-Glu-Lys-Phe-Asp-Lys-Ser',
    storage: '-20°C',
    inStock: true,
    featured: true,
  },
  {
    id: 'tb500-20',
    name: 'TB-500 20mg',
    slug: 'tb-500-20mg',
    description: 'High-dose muscle recovery peptide',
    price: 170,
    originalPrice: 180,
    category: 'Recovery',
    subcategory: 'Healing Peptides',
    dosage: '20mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    storage: '-20°C',
    inStock: true,
  },

  // ===== BLENDS & STACKS =====
  {
    id: 'blend-bb10',
    name: 'BPC-157 + TB-500 Blend 10mg',
    slug: 'bpc-tb-blend-10mg',
    description: 'Synergistic healing stack (5mg BPC-157 + 5mg TB-500)',
    price: 80,
    originalPrice: 85,
    category: 'Blends',
    subcategory: 'Recovery Stacks',
    dosage: '10mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    storage: '-20°C',
    inStock: true,
    featured: true,
  },
  {
    id: 'blend-bbg50',
    name: 'GLOW Blend 50mg',
    slug: 'glow-blend-50mg',
    description: 'GHK-Cu 35mg + TB-500 10mg + BPC-157 5mg',
    price: 140,
    originalPrice: 150,
    category: 'Blends',
    subcategory: 'Skin/Recovery',
    dosage: '50mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    storage: '-20°C',
    inStock: true,
  },
  {
    id: 'blend-ti17',
    name: 'Tesamorelin + Ipamorelin 17mg',
    slug: 'tesa-ipa-blend-17mg',
    description: 'Tesamorelin 11mg + Ipamorelin 6mg growth stack',
    price: 155,
    originalPrice: 165,
    category: 'Blends',
    subcategory: 'Growth Hormone',
    dosage: '17mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    storage: '-20°C',
    inStock: true,
  },

  // ===== GROWTH HORMONE SECRETAGOGUES =====
  {
    id: 'cjc-ipa5',
    name: 'CJC-1295 + Ipamorelin 5mg',
    slug: 'cjc-ipa-blend-5mg',
    description: 'CJC-1295 (no DAC) 2.5mg + Ipamorelin 2.5mg',
    price: 45,
    originalPrice: 50,
    category: 'Growth Hormone',
    subcategory: 'Secretagogues',
    dosage: '5mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    storage: '-20°C',
    inStock: true,
  },
  {
    id: 'cjc-dac5',
    name: 'CJC-1295 with DAC 5mg',
    slug: 'cjc-1295-dac-5mg',
    description: 'Long-acting growth hormone releasing hormone',
    price: 120,
    originalPrice: 130,
    category: 'Growth Hormone',
    subcategory: 'Secretagogues',
    dosage: '5mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    storage: '-20°C',
    inStock: true,
  },
  {
    id: 'ipamorelin5',
    name: 'Ipamorelin 5mg',
    slug: 'ipamorelin-5mg',
    description: 'Selective growth hormone releasing peptide',
    price: 30,
    originalPrice: 35,
    category: 'Growth Hormone',
    subcategory: 'GHRPs',
    dosage: '5mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    molecularWeight: '711.85 Da',
    sequence: 'Aib-His-D-2-Nal-D-Phe-Lys-NH2',
    storage: '-20°C',
    inStock: true,
    featured: true,
  },

  // ===== COGNITIVE ENHANCERS =====
  {
    id: 'selank5',
    name: 'Selank 5mg',
    slug: 'selank-5mg',
    description: 'Anxiolytic and cognitive enhancing peptide',
    price: 30,
    originalPrice: 35,
    category: 'Cognitive',
    subcategory: 'Nootropics',
    dosage: '5mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    molecularWeight: '751.85 Da',
    sequence: 'Thr-Lys-Pro-Arg-Pro-Gly-Pro',
    storage: '-20°C',
    inStock: true,
    featured: true,
  },
  {
    id: 'semax5',
    name: 'Semax 5mg',
    slug: 'semax-5mg',
    description: 'Neuroprotective and cognitive enhancer',
    price: 30,
    originalPrice: 35,
    category: 'Cognitive',
    subcategory: 'Nootropics',
    dosage: '5mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    molecularWeight: '813.91 Da',
    sequence: 'Met-His-Phe-Pro-Gly-Pro',
    storage: '-20°C',
    inStock: true,
    featured: true,
  },
  {
    id: 'blend-xs20',
    name: 'Selank + Semax Blend 20mg',
    slug: 'selank-semax-blend-20mg',
    description: 'Cognitive stack (10mg Selank + 10mg Semax)',
    price: 85,
    originalPrice: 90,
    category: 'Cognitive',
    subcategory: 'Nootropic Stacks',
    dosage: '20mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    storage: '-20°C',
    inStock: true,
  },

  // ===== SKIN & ANTI-AGING =====
  {
    id: 'ghk-cu50',
    name: 'GHK-Cu 50mg',
    slug: 'ghk-cu-50mg',
    description: 'Copper peptide for skin rejuvenation',
    price: 25,
    originalPrice: 30,
    category: 'Skin/Anti-Aging',
    subcategory: 'Copper Peptides',
    dosage: '50mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    molecularWeight: '401.9 Da',
    sequence: 'Gly-His-Lys',
    storage: '-20°C',
    inStock: true,
    featured: true,
  },
  {
    id: 'epithalon10',
    name: 'Epithalon 10mg',
    slug: 'epithalon-10mg',
    description: 'Telomerase activating peptide',
    price: 35,
    originalPrice: 40,
    category: 'Skin/Anti-Aging',
    subcategory: 'Anti-Aging',
    dosage: '10mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    molecularWeight: '389.4 Da',
    sequence: 'Ala-Glu-Asp-Gly',
    storage: '-20°C',
    inStock: true,
  },
  {
    id: 'mots-c10',
    name: 'MOTS-c 10mg',
    slug: 'mots-c-10mg',
    description: 'Mitochondrial-derived peptide',
    price: 50,
    originalPrice: 55,
    category: 'Skin/Anti-Aging',
    subcategory: 'Metabolic',
    dosage: '10mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    storage: '-20°C',
    inStock: true,
  },

  // ===== HORMONE & SEXUAL HEALTH =====
  {
    id: 'pt141-10',
    name: 'PT-141 10mg',
    slug: 'pt-141-10mg',
    description: 'Melanocortin agonist for sexual function research',
    price: 45,
    originalPrice: 50,
    category: 'Sexual Health',
    subcategory: 'Libido',
    dosage: '10mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    molecularWeight: '1025.2 Da',
    sequence: 'Ac-Nle-cyclo[Asp-His-D-Phe-Arg-Trp-Lys]-NH2',
    storage: '-20°C',
    inStock: true,
  },
  {
    id: 'kisspeptin5',
    name: 'Kisspeptin-10 5mg',
    slug: 'kisspeptin-10-5mg',
    description: 'Gonadotropin releasing hormone regulator',
    price: 40,
    originalPrice: 45,
    category: 'Sexual Health',
    subcategory: 'Hormone Regulation',
    dosage: '5mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    storage: '-20°C',
    inStock: true,
  },

  // ===== RESEARCH CHEMICALS & ACCESSORIES =====
  {
    id: 'nad100',
    name: 'NAD+ 100mg',
    slug: 'nad-plus-100mg',
    description: 'Nicotinamide adenine dinucleotide',
    price: 30,
    originalPrice: 35,
    category: 'Research Chemicals',
    subcategory: 'Anti-Aging',
    dosage: '100mg per vial',
    quantity: '10 vials',
    purity: '≥99%',
    storage: '-20°C',
    inStock: true,
  },
  {
    id: 'bac-water3',
    name: 'BAC Water 3ml',
    slug: 'bac-water-3ml',
    description: 'Bacteriostatic water for reconstitution',
    price: 9,
    originalPrice: 10,
    category: 'Accessories',
    subcategory: 'Reconstitution',
    dosage: '3ml per vial',
    quantity: '10 vials',
    purity: '=100%' ,
    storage: 'Room Temperature',
    inStock: true,
  },
];

export const categories = [
  { id: 'weight-loss', name: 'Weight Loss', count: 15 },
  { id: 'recovery', name: 'Recovery & Healing', count: 12 },
  { id: 'growth-hormone', name: 'Growth Hormone', count: 10 },
  { id: 'cognitive', name: 'Cognitive Enhancers', count: 8 },
  { id: 'skin-anti-aging', name: 'Skin & Anti-Aging', count: 10 },
  { id: 'sexual-health', name: 'Sexual Health', count: 6 },
  { id: 'blends', name: 'Blends & Stacks', count: 8 },
  { id: 'accessories', name: 'Accessories', count: 3 },
];

export const getProductsByCategory = (category: string) => {
  return products.filter(product => product.category === category);
};

export const getFeaturedProducts = () => {
  return products.filter(product => product.featured);
};